services:
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__PostgreSQL=Server=catalogdb;Port=5432;Database=catalogdb;User Id=postgres;Password=33jkhj2940j91hx8;Include Error Detail=true
    depends_on:
      - catalogdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=33jkhj2940j91hx8
      - POSTGRES_DB=catalogdb
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__PostgreSQL=Server=basketdb;Port=5433;Database=basketdb;User Id=postgres;Password=1a2b8ousjdlfsdlk;Include Error Detail=true
      - ConnectionStrings__Redis=basketcache:6379
    depends_on:
      - basketdb
      - basketcache
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  basketdb:
    container_name: basketdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1a2b8ousjdlfsdlk
      - POSTGRES_DB=basketdb
    restart: always
    ports: 
      - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data/

  basketcache:
    container_name: basketcache
    restart: always
    ports:
      - "6379:6379"
